Repository kube-arbiter/arbiter, pull requests merged in 2022-10, with the labels that each got.

#6 chore: update CI and goreportcard badge
  README.md
Labels: size/XS

#8 fix: e2e script error exit
  pkg/executor/observabilityactionpolicy_controller.go
  pkg/fetch/fetch.go
  tests/install-infra.sh
Labels: size/S

#9 context logger with klog, flag parsing plugin
  cmd/executor/main.go
  pkg/common/controller_options.go
  pkg/common/flags.go
  pkg/common/klog.go
  pkg/common/rest_config.go
  pkg/executor/observabilityactionpolicy_controller.go
  vendor/k8s.io/klog/v2/klogr/README.md
  vendor/k8s.io/klog/v2/klogr/klogr.go
  vendor/modules.txt
Labels: size/L

#13 context logger with klog
  pkg/executor/observabilityindicant_controller.go
Labels: size/S

#15 chore: auto add reviewers
  .github/auto_request_review.yml
  .github/workflows/auto_assign_reviewers.yml
Labels: size/M

#20 fix: auto assign reviews workflow has no permissions
  .github/auto_request_review.yml
  .github/workflows/auto_assign_reviewers.yml
Labels: size/S

#18 update charts version
  charts/arbiter/Chart.yaml
Labels: size/XS

#17 add liveness probe for observer
  charts/arbiter/templates/deployment-metric-server.yaml
  charts/arbiter/templates/deployment-prometheus.yaml
  manifests/install/observer/observer-metric-server.yaml
  manifests/install/observer/observer-prometheus.yaml
Labels: size/S

#16 fix: some issue found by golangci-lint
  .golangci.yaml
  cmd/executor/main.go
  pkg/common/controller_options.go
  pkg/common/klog.go
  pkg/common/rest_config.go
  pkg/controller/controller.go
  pkg/executor/observabilityactionpolicy_controller.go
Labels: size/S

#22 fix: make auto request review rework
  .github/auto_request_review.yml
  .github/workflows/auto_assign_reviewers.yml
Labels: size/S

#21 Make executor more general to support more data of OAP
  charts/arbiter/crds/arbiter.k8s.com.cn_observabilityactionpolicies.yaml
  manifests/crds/arbiter.k8s.com.cn_observabilityactionpolicies.yaml
  manifests/example/executor/resource-tagger/metric-server-node-cpu.yaml
  manifests/example/executor/resource-tagger/metric-server-node-mem.yaml
  manifests/example/executor/resource-tagger/metric-server-pod-cpu.yaml
  manifests/example/executor/resource-tagger/metric-server-pod-mem.yaml
  manifests/example/executor/resource-tagger/prometheus-node-cpu.yaml
  manifests/example/executor/resource-tagger/prometheus-node-mem.yaml
  manifests/example/executor/resource-tagger/prometheus-pod-cpu.yaml
  manifests/example/executor/resource-tagger/prometheus-pod-mem.yaml
  pkg/apis/v1alpha1/executor_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/commands/get/get.go
  pkg/controller/controller.go
  pkg/executor/observabilityactionpolicy_controller.go
  pkg/proto/README.md
  pkg/proto/executor.proto
  pkg/proto/lib/executor/execute.pb.go
  pkg/proto/lib/executor/executor.pb.go
  pkg/proto/lib/executor/executor_grpc.pb.go
  pkg/proto/lib/observer/observiability.pb.go
  pkg/proto/lib/observer/observiability_grpc.pb.go
  tests/install-infra.sh
Labels: size/XL

#23 enhance code readability
  pkg/controller/controller.go
Labels: size/L

#25 feat: helm lint
  hack/verify-all.sh
  hack/verify-helm.sh
Labels: size/S

#24 Update yaml files format and remove some config
  charts/arbiter/templates/deployment-metric-server.yaml
  charts/arbiter/templates/deployment-prometheus.yaml
  charts/arbiter/templates/deployment.yaml
  manifests/install/executor/executor-resource-tagger.yaml
Labels: size/S

#26 add icon to chart package
  charts/arbiter/Chart.yaml
Labels: size/XS

#27 fix: controller unit test failed
  pkg/controller/controller_test.go
Labels: size/M

#29 cleanup: update golang.sh
  hack/lib/golang.sh
Labels: size/XS

#30 cleanup: use tag dev for plugin in tests
  tests/install-infra.sh
Labels: size/S

#32 fix: drop non-inherited context in executor
  pkg/executor/observabilityactionpolicy_controller.go
  pkg/executor/observabilityindicant_controller.go
Labels: size/M

#33 Support to get general metrics that does not depend on pod/node resource
  cmd/observer/main.go
  manifests/crds/arbiter.k8s.com.cn_observabilityindicants.yaml
  manifests/example/observer/metric/metric-server-node-cpu.yaml
  manifests/example/observer/metric/metric-server-node-mem.yaml
  manifests/example/observer/metric/metric-server-pod-cpu.yaml
  manifests/example/observer/metric/metric-server-pod-mem.yaml
  manifests/example/observer/prometheus/prometheus-node-cpu.yaml
  manifests/example/observer/prometheus/prometheus-node-mem.yaml
  pkg/apis/v1alpha1/observer_types.go
  pkg/controller/controller.go
  pkg/fetch/fetch.go
Labels: size/L

#36 Add more prometheus samples
  .github/workflows/e2e.yml
  manifests/example/observer/prometheus/prometheus-cluster-schedulable-cpu.yaml
  manifests/example/observer/prometheus/prometheus-max-available-cpu.yaml
  manifests/example/observer/prometheus/prometheus-rawdata-node-unschedule.yaml
  tests/e2e/observer_test.go
  tests/install-infra.sh
  tests/prepare-k8s.sh
Labels: size/L

#37 feat: add linter gocritic
  .golangci.yaml
  pkg/controller/controller.go
  pkg/executor/observabilityactionpolicy_controller.go
  pkg/extend/manager/manager.go
Labels: size/S

#31 split code
  pkg/controller/controller.go
  pkg/controller/helper.go
Labels: size/L

#34 fix: make linter contextcheck work
  .golangci.yaml
Labels: size/XS

#41 feat: executor support various actions
  charts/arbiter/crds/arbiter.k8s.com.cn_observabilityactionpolicies.yaml
  manifests/crds/arbiter.k8s.com.cn_observabilityactionpolicies.yaml
  manifests/example/executor/resource-tagger/metric-server-node-cpu.yaml
  manifests/example/executor/resource-tagger/metric-server-node-mem.yaml
  manifests/example/executor/resource-tagger/metric-server-pod-cpu.yaml
  manifests/example/executor/resource-tagger/metric-server-pod-mem.yaml
  manifests/example/executor/resource-tagger/prometheus-node-cpu.yaml
  manifests/example/executor/resource-tagger/prometheus-node-mem.yaml
  manifests/example/executor/resource-tagger/prometheus-pod-cpu.yaml
  manifests/example/executor/resource-tagger/prometheus-pod-mem.yaml
  pkg/apis/v1alpha1/executor_types.go
  pkg/executor/observabilityactionpolicy_controller.go
  pkg/proto/README.md
  pkg/proto/executor.proto
  pkg/proto/lib/executor/executor.pb.go
  pkg/proto/lib/executor/executor_grpc.pb.go
Labels: size/L

#46 fix: check obi data in e2e tests
  .github/workflows/e2e.yml
  manifests/example/observer/prometheus/prometheus-cluster-schedulable-cpu.yaml
  manifests/example/observer/prometheus/prometheus-max-available-cpu.yaml
  manifests/example/observer/prometheus/prometheus-node-cpu.yaml
  manifests/example/observer/prometheus/prometheus-node-mem.yaml
  tests/install-infra.sh
  tests/prepare-k8s.sh
Labels: size/M

#48 feat: add workflow to sync file to pre branch
  .github/sync.yml
  .github/workflows/sync.yml
Labels: size/M

#45 fix: update script for pre branch
  .github/workflows/e2e.yml
  .github/workflows/release.yml
  cmd/scheduler/main.go
  manifests/install/scheduler/kube-scheduler-new.yaml
  pkg/extend/manager/manager.go
  tests/prepare-k8s.sh
Labels: size/L

#50 cleanup: update sync file list
  .github/sync.yml
Labels: size/XS

#52 fix: make pre tests run again
  hack/verify-helm.sh
  manifests/install/scheduler/kube-scheduler-arbiter-config.yaml
Labels: size/S

#51 feat: redefine executor actions
  manifests/crds/arbiter.k8s.com.cn_observabilityactionpolicies.yaml
  manifests/example/executor/resource-tagger/metric-server-node-cpu.yaml
  manifests/example/executor/resource-tagger/metric-server-node-mem.yaml
  manifests/example/executor/resource-tagger/metric-server-pod-cpu.yaml
  manifests/example/executor/resource-tagger/metric-server-pod-mem.yaml
  manifests/example/executor/resource-tagger/prometheus-node-cpu.yaml
  manifests/example/executor/resource-tagger/prometheus-node-mem.yaml
  manifests/example/executor/resource-tagger/prometheus-pod-cpu.yaml
  manifests/example/executor/resource-tagger/prometheus-pod-mem.yaml
  pkg/apis/v1alpha1/executor_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/executor/observabilityactionpolicy_controller.go
  pkg/proto/executor.proto
  pkg/proto/lib/executor/executor.pb.go
  pkg/proto/lib/executor/executor_grpc.pb.go
Labels: size/L

#54 🔄 Synced file(s) with kube-arbiter/arbiter
  manifests/crds/arbiter.k8s.com.cn_observabilityactionpolicies.yaml
  pkg/apis/v1alpha1/executor_types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
Labels: size/S, auto-sync

#53 feat: add test cases for utils package
  pkg/utils/util_test.go
Labels: size/S

#55 feat: add concurrency args in github action
  .github/workflows/codeql.yml
  .github/workflows/e2e.yml
Labels: size/XS

#56 feat: add concurrency args in github action
  .github/dependabot.yml
  .github/workflows/codeql.yml
  .github/workflows/e2e.yml
Labels: size/S

#57 fix: remove me as sync workflow reviewer
  .github/workflows/sync.yml
Labels: size/XS

#58 🔄 Synced file(s) with kube-arbiter/arbiter
  pkg/utils/util_test.go
Labels: size/S, auto-sync
