Repository kube-arbiter/arbiter, pull requests merged in 2022-11, with the labels that each got.

#61 feat: observer merge plugin
  charts/arbiter/templates/deployment-metric-server.yaml
  charts/arbiter/templates/observer-plugins.yaml
  charts/arbiter/values.yaml
  manifests/example/observer/metric/metric-server-node-cpu.yaml
  manifests/example/observer/metric/metric-server-node-mem.yaml
  manifests/example/observer/metric/metric-server-pod-cpu.yaml
  manifests/example/observer/metric/metric-server-pod-mem.yaml
  manifests/install/observer/observer-plugins.yaml
  manifests/install/observer/observer-prometheus.yaml
  pkg/controller/controller.go
  pkg/fetch/fetch.go
  pkg/proto/lib/observer/observiability.pb.go
  pkg/proto/lib/observer/observiability_grpc.pb.go
  pkg/proto/observiability.proto
  tests/e2e/scheduler_test.go
  tests/install-infra.sh
Labels: size/XL

#64 update readme of the arbiter chart
  charts/arbiter/README.md
Labels: size/S

#66 chore(deps): bump github.com/onsi/gomega from 1.22.1 to 1.24.0
  .github/workflows/e2e.yml
  go.mod
  go.sum
  vendor/github.com/blizzy78/varnamelen/varnamelen.code-workspace
  vendor/github.com/go-errors/errors/cover.out
  vendor/github.com/onsi/gomega/.gitignore
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/RELEASING.md
  vendor/github.com/onsi/gomega/format/format.go
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/assertion.go
  vendor/github.com/onsi/gomega/internal/async_assertion.go
  vendor/github.com/onsi/gomega/internal/duration_bundle.go
  vendor/github.com/onsi/gomega/internal/gomega.go
  vendor/github.com/onsi/gomega/internal/polling_signal_error.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/types/types.go
  vendor/modules.txt
Labels: size/XS

#67 controller renamed to observer
  cmd/observer/main.go
  pkg/observer/helper.go
  pkg/observer/observer.go
  pkg/observer/observer_test.go
Labels: size/S

#72 Synced files with main and update
  Makefile
  cmd/scheduler/main.go
  cmd/scheduler/main_test.go
  hack/fix-golang-lint-error.sh
  hack/tools/tools.go
  pkg/scheduler/manager/manager.go
  pkg/scheduler/manager/metrics.go
  pkg/scheduler/scheduler.go
  tests/prepare-k8s.sh
Labels: size/L

#71 cleanup: rename Manager1 to manager
  pkg/scheduler/manager/manager.go
  pkg/scheduler/scheduler.go
Labels: size/M

#70 fix: update the image in the doc
  doc/install.md
Labels: size/XS

#75 feat: github action auto use ginkgo version in go.mod
  .github/workflows/e2e.yml
Labels: size/S

#77 fix wrong test cases
  tests/e2e/observer_test.go
  tests/e2e/util_test.go
Labels: size/M

#79 refine code and fix metrics adapter issue
  charts/arbiter/Chart.yaml
  charts/arbiter/README.md
  charts/arbiter/templates/executor-rbac.yaml
  charts/arbiter/templates/executor.yaml
  charts/arbiter/templates/observer.yaml
  charts/arbiter/values.yaml
  doc/install.md
  manifests/example/adapter/hpa-using-obi.yaml
  manifests/example/adapter/obi-cpu-metrics.yaml
  manifests/example/adapter/service-hpa-demo.yaml
  manifests/example/executor/metric-server-node-cpu.yaml
  manifests/example/executor/metric-server-node-mem.yaml
  manifests/example/executor/metric-server-pod-cpu.yaml
  manifests/example/executor/metric-server-pod-mem.yaml
  manifests/example/executor/prometheus-node-cpu.yaml
  manifests/example/executor/prometheus-node-mem.yaml
  manifests/example/executor/prometheus-pod-cpu.yaml
  manifests/example/executor/prometheus-pod-mem.yaml
  manifests/install/executor/executor.yaml
  manifests/install/metrics-adapter/obi-adapter.yaml
  manifests/install/observer/observer.yaml
  pkg/adapter/provider/provider.go
  tests/install-infra.sh
Labels: size/L

#83 fix: use cert-manager v1.8.2 in k8s 1.20-
  tests/install-infra.sh
Labels: size/XS
